### ISSUE TITLE
These patches should be applied before package building, otherwise it does not work for us

### ISSUE THREAD

**Issue by wangli5665** [CKI-project/tests-beaker#476]
https://github.com/CKI-project/tests-beaker/blob/e159a39fc0e885f9cedfd0acbae2446407bf9c6c/distribution/ltp-upstream/lite/runtest.sh#L80-L82

**Comment by veruu** [comment]
cc @rasibley , can you take a look at fixing this?

**Comment by emanchado** [comment]
I seem to recall that the second patch (which I introduced) can be removed, because I think it never properly fixed what I was trying to fix. I imagine the first one is still valid, though.

**Comment by veruu** [comment]
Fixed in https://github.com/CKI-project/tests-beaker/commit/34e1f2616c9de0c923289483c8406a4aa6002774 , closing

**Comment by rasibley** [comment]
Thanks ! I overlooked the issue, thanks for closing. @emanchado fyi this is why fs_fill was still failing :woman_facepalming:

**Comment by emanchado** [comment]
Oh, no! So we were applying the patches *after* compiling?? :man_facepalming: indeed :sweat_smile:
